### ISSUE TITLE
Android 5 test - crash feedback

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-path-zeir#207]
V.2.0.3-R2 (Prod)
Test device: Android 5.1.1.
- [ ] The sync on Android 5 is very slow and kept logging out while on the 10,sync was quiet fast and it did not log out until sync was completed.
- [ ] Android 5 is crushing when you select add child, the screen blacks out for some seconds then gives an error( fetal error has occurred, contact your systems administrator). 
- [ ] Android 5 still has the error, ZEIR is not responding.

**Comment by junaidwarsivd** [comment]
@AnnieMungai  only one crash is reported for android 5.1.1 on firebase crashlytics in last 15 days 
 Fatal Exception: com.vijay.jsonwizard.exceptions.JsonFormRuntimeException: Could not fetch context
       at com.vijay.jsonwizard.customviews.GenericTextWatcher.afterTextChanged(GenericTextWatcher.java:70)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:7789)
       at android.widget.TextView.setText(TextView.java:4118)
       at android.widget.TextView.setText(TextView.java:3967)
       at android.widget.EditText.setText(EditText.java:85)
       at android.widget.TextView.setText(TextView.java:3942)
       at com.vijay.jsonwizard.activities.JsonFormActivity$7.run(JsonFormActivity.java:1944)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5601)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by AnnieMungai** [comment]
v.0.0.25
Looks good!
